In [57]:
import os
os.environ["OLLAMA_HOST"] = "http://localhost:11460" 
print(os.environ.get("OLLAMA_HOST"))

http://localhost:11460

In [58]:
pip install -r requirements.txt

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: pydantic in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.12.5)
Requirement already satisfied: langchain in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.3.27)
Requirement already satisfied: langchain-core in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.3.80)
Requirement already satisfied: langchain-community in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.3.31)
Requirement already satisfied: langchain-ollama in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.3.10)
Requirement already satisfied: scikit-learn in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (1.6.1)
Requirement already satisfied: numpy>=1.22.4 in /home/bumu60du/.local/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/bumu60du/.local/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/bumu60du/.local/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic->-r requirements.txt (line 2)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic->-r requirements.txt (line 2)) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic->-r requirements.txt (line 2)) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic->-r requirements.txt (line 2)) (0.4.2)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (0.3.11)
Requirement already satisfied: langsmith>=0.1.17 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (0.4.37)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (2.0.44)
Requirement already satisfied: requests<3,>=2 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (2.32.5)
Requirement already satisfied: PyYAML>=5.3 in /usr/lib64/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (5.4.1)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (4.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-core->-r requirements.txt (line 4)) (9.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-core->-r requirements.txt (line 4)) (1.33)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-core->-r requirements.txt (line 4)) (25.0)
Requirement already satisfied: jsonpointer>=1.9 in /home/bumu60du/.local/lib/python3.9/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->-r requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /home/bumu60du/.local/lib/python3.9/site-packages (from langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (0.25.0)
Requirement already satisfied: anyio in /home/bumu60du/.local/lib/python3.9/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (4.11.0)
Requirement already satisfied: certifi in /home/bumu60du/.local/lib/python3.9/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /home/bumu60du/.local/lib/python3.9/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (1.0.9)
Requirement already satisfied: idna in /usr/lib/python3.9/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (2.10)
Requirement already satisfied: h11>=0.16 in /home/bumu60du/.local/lib/python3.9/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/bumu60du/.local/lib/python3.9/site-packages (from requests<3,>=2->langchain->-r requirements.txt (line 3)) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests<3,>=2->langchain->-r requirements.txt (line 3)) (1.26.5)
Requirement already satisfied: greenlet>=1 in /home/bumu60du/.local/lib/python3.9/site-packages (from SQLAlchemy<3,>=1.4->langchain->-r requirements.txt (line 3)) (3.2.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-community->-r requirements.txt (line 5)) (3.13.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-community->-r requirements.txt (line 5)) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-community->-r requirements.txt (line 5)) (2.11.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-community->-r requirements.txt (line 5)) (0.4.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (0.9.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->-r requirements.txt (line 5)) (1.2.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied: ollama<1.0.0,>=0.5.3 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-ollama->-r requirements.txt (line 6)) (0.6.1)
Requirement already satisfied: scipy>=1.6.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from scikit-learn->-r requirements.txt (line 7)) (1.10.1)
Requirement already satisfied: joblib>=1.2.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from scikit-learn->-r requirements.txt (line 7)) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from scikit-learn->-r requirements.txt (line 7)) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/bumu60du/.local/lib/python3.9/site-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (1.3.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [59]:
import prompts as prompts

In [60]:
import importlib
importlib.reload(prompts)

In [61]:
import numpy as np
import pandas as pd
from langchain_ollama import OllamaLLM
from langchain_core.prompts import PromptTemplate
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

In [62]:
from prompts import Config

In [63]:
# Load your CSV
df_new = pd.read_csv("/home/bumu60du/fake_review_detection/Datasets/Amazon_Human_VS_ComputerFake.csv")
reviews = df_new["text"].tolist()

In [64]:
prompt = PromptTemplate(
    input_variables=["text"], # the placeholder to be replaced based on prompt template
    template=Config.zero_shot_prompt_template
)

# Load small model
llm = OllamaLLM(model=Config.model)

# Create chain using pipe operator (modern LangChain syntax)
chain = prompt | llm

In [65]:
print(Config.zero_shot_prompt_template)

    You are an expert at detecting fake and real reviews.

    Task: Classify the following review of a product that is listed on amazon as either "fake" or "real". Analyze the language and structure of the review,
	It should not be overly generic or templeted language,should not have sales-like wording.

    Review: "{text}"

    Classify this review as either "fake" or "real" (respond with only one word):

In [66]:
# # Classify each review
# results = []
# for r in reviews:
#     result = chain.invoke({"text": r})
#     # Clean the output - extract only "truthful" or "deceptive"
#     label = result.strip().lower()
#     # Extract first word if model adds extra text
#     if " " in label:
#         label = label.split()[0]
#     # Remove any punctuation
#     label = label.strip('.,!?;:')
#     print(f"Raw output: {result} -> Cleaned: {label}")
#     results.append(label)

In [67]:
# Classify each review
results = []

for r in reviews:
    result = chain.invoke({"text": r})
    
    label = result.strip().lower()
    
    # Keep only valid labels
    if "fake" in label:
        cleaned_label = "fake"
    elif "real" in label:
        cleaned_label = "real"
    else:
        print(f"Skipping invalid output: {result}")
        continue  # skip this review
    cleaned_label = cleaned_label.strip('.,!?;:')
    print(f"Raw output: {result} -> Cleaned: {cleaned_label}")
    results.append(cleaned_label)

Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and descriptive feedback on the product's appearance, construction, and color. It also suggests that the reviewer plans to purchase the product as a gift, indicating a genuine interest in the product. -> Cleaned: real
Raw output: Real.

The review uses natural language and expresses genuine enthusiasm for the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is concise and descriptive, indicating genuine experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed, personal, and specific experiences and opinions about the product, indicating genuine engagement and experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's performance and quality, suggesting that the reviewer has actually used the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and detailed feedback on the product's functionality and design features, suggesting that the reviewer has actually used the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses descriptive language and expresses genuine enthusiasm for the product, indicating a likely authentic experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experiences that suggest genuine usage and knowledge of the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses enthusiastic and personal language, indicating a genuine experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and offers no meaningful insight into the product's heat-deflecting properties. -> Cleaned: fake
Raw output: Real.

The review provides detailed and specific observations about the product's size, patterns, and aesthetic appeal, suggesting genuine experience and opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific feedback on the product's features and functionality, suggesting that the author has actually used the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks coherence and logic, and exhibits nonsensical advice. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and detailed feedback on the product's size, fit, and durability, suggesting genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific information about the product, indicating that the reviewer has actually used it and has positive experiences with it. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks detail and offers no meaningful analysis of the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses personal language and describes actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the knife's quality and materials, suggesting that the reviewer has actually used and evaluated the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific information about the product's performance and limitations, indicating genuine experience and knowledge about the Zebco product. -> Cleaned: real
Raw output: Fake.

The review lacks detail and exhibits illogical behavior. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's performance and value for money, indicating that the author has actually used it. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses exaggerated language and claims that the product exceeded expectations despite providing no specific details about its functionality or performance. Additionally, the mention of receiving a discount in exchange for the review raises suspicion. -> Cleaned: fake
Raw output: Real.

The review provides specific details about how the socks work for various situations, indicating genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's usefulness, delivery speed, and intended use as a gift. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's fit and durability, suggesting genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and detailed feedback on the product's resistance levels and their effectiveness for different parts of the body. It also expresses excitement about trying out the product and highlights noticeable improvements in the reviewer's workout. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and observations about the product, indicating genuine experience and knowledge of its features. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides a concise and honest assessment of the product, mentioning only a minor issue with the included screwdriver. The language is clear and natural, indicating a genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the fit of the case on different MacBook models, indicating actual usage and experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses excessive repetition and a robotic tone, suggesting it is not written by a genuine user. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides a personal anecdote and expresses an opinion based on their experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's performance and a personal experience with a similar product, indicating authenticity. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses specific and descriptive language, indicating actual experience with the product. It avoids generic or templated language commonly used in fake reviews. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a personal opinion about the size of the product and its compatibility with the iPad mini, providing specific details. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experiences, suggesting genuine use and evaluation of the product. -> Cleaned: real
Raw output: Real.

The review provides a concise and honest opinion of the product, mentioning both its speed and case design. It lacks the typical sales-like language often found in fake reviews. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and descriptive details about the product's issues, suggesting that the reviewer actually experienced these problems. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a clear and specific disappointment with the product's ineffectiveness, providing a personal anecdote about the CD rom issue. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about how the adapter works with a Bose Wave radio and mentions a compatibility issue with the CD changer, suggesting actual usage and technical understanding. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review contains specific details and technical language suggesting actual experience and knowledge of computer hardware. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and honest feedback about the product's functionality and durability. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The language is specific and indicates that the reviewer has experience using the product in a professional setting. -> Cleaned: real
Raw output: Real.

The review provides specific information about the product's affordability and performance, suggesting genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's aesthetics and installation process, suggesting genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses specific and descriptive language indicating an actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific information about the product's features, functionality, and customer service experiences, suggesting genuine experience and knowledge of the product. -> Cleaned: real
Raw output: Real.

The review provides specific and descriptive criticisms of the product's air flow, shape, and light control, suggesting that the reviewer has actually used and experienced these issues firsthand. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review exhibits sophisticated vocabulary, detailed analysis of the film's elements, and a clear understanding of its cinematic context. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review solely focuses on praising the script and acting, without providing any meaningful critique or analysis of the product itself. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides honest and constructive criticism of the product, focusing on specific aspects such as acting and story. -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses repetitive language, suggesting a lack of genuine opinion. -> Cleaned: fake
Raw output: Real.

The review provides a personal and thoughtful opinion about the movie, indicating genuine enjoyment and a connection to the film's quality. -> Cleaned: real
Raw output: Fake.

The review is overly repetitive and uses a template-like structure, suggesting it is fake. -> Cleaned: fake
Raw output: Real.

The review expresses an honest opinion about the adaptation, noting that it is similar to the book but with different characters. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is excessively repetitive and lacks meaningful content beyond simply listing the word "thriller" multiple times. -> Cleaned: fake
Raw output: Fake.

The review is excessively repetitive and contains highly redundant language, suggesting a lack of authenticity. -> Cleaned: fake
Raw output: Fake.

The review is overly repetitive and uses redundant language, suggesting a lack of authenticity. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is excessively repetitive and uses a formulaic structure, indicating that it is likely fake. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is excessively laudatory and uses repetitive language, indicating a lack of authenticity. -> Cleaned: fake
Raw output: Real.

The review expresses a genuine opinion about the lack of chemistry between the characters in the movie. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is overly enthusiastic and uses generic language that suggests it is not written by a genuine consumer. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a genuine opinion about the product, providing specific feedback about different parts of it. -> Cleaned: real
Raw output: Real.

The review provides a detailed and honest critique of the product's picture quality and movie content, suggesting that the reviewer has actually used the product and has a genuine opinion. -> Cleaned: real
Raw output: Fake.

The review uses highly exaggerated and unnatural language, and lacks sincerity and specificity. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks detail and exhibits excessive hyperbole, suggesting a fabricated opinion. -> Cleaned: fake
Raw output: Fake.

The review lacks specificity and uses generic, superlative language that is often found in fake reviews. -> Cleaned: fake
Raw output: Real.

The review expresses genuine excitement and familiarity with Hanna-Barbera, suggesting a genuine fandom. -> Cleaned: real
Raw output: Fake.

The review lacks coherence and appears to be a random assortment of words and phrases with no meaningful content related to the product. -> Cleaned: fake
Raw output: Real.

The review uses descriptive language and expresses a genuine opinion, suggesting that the writer has actually watched the movie. -> Cleaned: real
Raw output: Real.

The review demonstrates an understanding of both Polish and German languages and their use in the movie, suggesting genuine knowledge of the subject matter. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses a repetitive and formulaic structure, indicating a lack of authenticity. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses exaggerated and enthusiastic language, suggesting that it is not a genuine and thoughtful opinion. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a negative and well-articulated opinion of the movie, without using overly generic or promotional language. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses humor and playful language indicating it's not a genuine product review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real

In [68]:
df_new.head(10)

,Binary_label,Category,source,text,is_synthetic
0,fake,Home_and_Kitchen,amazon,Air pressure was utter crap. I kept the lid o...,1
1,fake,Home_and_Kitchen,amazon,"Not what I expected, smaller than expected, bu...",1
2,fake,Home_and_Kitchen,amazon,We like a toaster that doesn't have the long h...,1
3,fake,Home_and_Kitchen,amazon,Love these pans they work great. The only prob...,1
4,fake,Home_and_Kitchen,amazon,I love the print on the back and the finish. I...,1
5,fake,Home_and_Kitchen,amazon,Bought this on a whim and it was the best purc...,1
6,fake,Home_and_Kitchen,amazon,"I admit I was leary of the suction, but I did ...",1
7,fake,Home_and_Kitchen,amazon,Purchased one as a gift and it was a very nice...,1
8,fake,Home_and_Kitchen,amazon,I wanted something to hold a bunch of pieces o...,1
9,fake,Home_and_Kitchen,amazon,I'm so happy I found this set and am very plea...,1

In [69]:
# def clean_label(text):
#     return text.strip().lower().split()[0].strip('.,!?;:')
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

def evaluate_model(df, results):
    # Get true labels from the dataframe
    #y_true = df["deceptive"].tolist()
    y_true = df["Binary_label"].tolist()
    y_pred = results

    # Calculate metrics
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='weighted', pos_label=None)
    conf_matrix = confusion_matrix(y_true, y_pred)

    return accuracy, f1, conf_matrix

In [70]:
y_true = df_new["Binary_label"].tolist()

In [71]:
for label in results:
    print(label)

real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
fake
real
fake
real
real
real
fake
fake
fake
real
real
real
fake
real
fake
real
real
fake
real
real
real
real
fake
real
fake
fake
real
fake
real
real
real
fake
real
real
real
real
real
real
fake
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
fake
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
fake
real
real
real
real
real
real
fake
real
real
fake
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real
fake
real
real
real
real
real
real
real
real
real
real
real
real
real
real
real

In [72]:
accuracy, f1, conf_matrix = evaluate_model(df_new, results)

print("=" * 50)
print("ZERO-SHOT PROMPTING RESULTS")
print(Config.model)
print("=" * 50)
print("Accuracy:", accuracy)
print("\nF1 Score:", f1)
print("\nConfusion Matrix:")
print(conf_matrix)
print("=" * 50)

==================================================
ZERO-SHOT PROMPTING RESULTS
gemma:7b
==================================================
Accuracy: 0.51875

F1 Score: 0.4040236145967775

Confusion Matrix:
[[ 32 368]
 [ 17 383]]
==================================================

## One-Shot Prompting
Using one example to guide the model's classification

In [73]:
llm = OllamaLLM(model=Config.model)

In [74]:
one_shot_prompt = PromptTemplate(
    input_variables=["text"],
    template = Config.one_shot_prompt_template
)
# Create one-shot chain
one_shot_chain = one_shot_prompt | llm

In [75]:
print(Config.one_shot_prompt_template)

     You are an expert at detecting fake and real reviews.

    Task: Classify the following review of a product that is listed on amazon as either "real" or "fake". Analyze the language and structure of the review,
	It should not be overly generic or templeted language,should not have sales-like wording and lacks details or specificity.

    Example:
    Review: "Great Watch. I have had this watch for a long time and it works great. I have one in my car and the other in my office. The watch itself is a great watch and is very easy to use. It is a perfect size for my wrist and is very easy to wear. I have used it with a portable watch and I can tell the watch is very well made. I have worn it with a watch band and it is very comfortable. I will buy another one for my phone. I would highly recommend this watch.Perfect for my kids. I love them.These are super lightweight and lightweight. I have used them for a couple of months and they are still working great. I would definitely recommend them to my son for those times when he is not going to be wearing a helmet.These work great. I have used them for about a month and they are still doing great.Works as advertised.This is my second pair of glasses, and I really like the quality of the material. The material is thin and very soft, and it's comfortable to wear. The material is also very easy to clean, and I haven't had a problem with the plastic being damaged. I also have the odd case on my older pair, which I got for my husband when I was a kid. The fact that it's made of a durable material is"
    Classification: fake

    Now classify this review:
    Review: "{text}"
    Classify this review as either "real" or "fake" (respond with only one word):

In [76]:
# # Classify each review
# one_shot_results = []
# for r in reviews:
#     result = one_shot_chain.invoke({"text": r})
#     # Clean the output - extract only "truthful" or "deceptive"
#     label = result.strip().lower()
#     # Extract first word if model adds extra text
#     if " " in label:
#         label = label.split()[0]
#     # Remove any punctuation
#     label = label.strip('.,!?;:')
#     print(f"Raw output: {result} -> Cleaned: {label}")
#     one_shot_results.append(label)

In [77]:
# Classify each review
one_shot_results = []

for r in reviews:
    result = one_shot_chain.invoke({"text": r})
    
    label = result.strip().lower()
    
    # Keep only valid labels
    if "fake" in label:
        cleaned_label = "fake"
    elif "real" in label:
        cleaned_label = "real"
    else:
        print(f"Skipping invalid output: {result}")
        continue  # skip this review
    cleaned_label = cleaned_label.strip('.,!?;:')
    print(f"Raw output: {result} -> Cleaned: {cleaned_label}")
    one_shot_results.append(cleaned_label)

Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and originality. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real.

The review provides specific details and personal experiences, indicating genuine use and appreciation of the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, uses generic language, and lacks a detailed analysis of the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks detail, offers no context or explanation, and focuses solely on a negative experience. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language, suggesting it's fake. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experience about the product's effectiveness in reducing recoil for a specific firearm. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity, and sales-like wording. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, offers generic language, and lacks detailed analysis or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides thoughtful and specific commentary on the movie's plot, characters, and acting, indicating a genuine opinion. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity, fails to provide any concrete details or personal experiences, and simply repeats generic statements about the quality of the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity, originality, and critical analysis. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specificity, originality and fails to provide insightful details or personal experiences. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks a personal touch. -> Cleaned: fake
Raw output: Fake.

The review lacks details, specificity, and originality in its language. It simply repeats the same phrase "The script is excellent" multiple times, indicating a lack of genuine enthusiasm or personal experience. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks a personal touch. -> Cleaned: fake
Raw output: Real.

The review provides detailed analysis of the movie's writing, acting, story and visuals, suggesting a genuine opinion. -> Cleaned: real
Raw output: Fake.

The review lacks specifics, genuine insights or personal experiences. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity, details, and genuine opinions, exhibiting templated language. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, generic language, and fails to provide detailed analysis or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, originality and detailed analysis, resembling a generic promotional blurb. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides thoughtful analysis and personal insights, indicating genuine engagement with the movie. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specific details or analysis of the product, and uses generic language commonly found in fake reviews. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides thoughtful analysis of the film, noting specific strengths and weaknesses. It exhibits genuine interest in the movie and offers well-articulated opinions. -> Cleaned: real
Raw output: Real.

The review provides thoughtful analysis and genuine opinions about the movie, indicating that the reviewer is a genuine consumer. -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity, and provides no useful information about the product. It reads like a promotional tagline or a piece of clickbait rather than a genuine review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language, and lacks details about the product's performance or features. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details and specifics, uses templated language, and focuses on promoting the product rather than providing an objective assessment. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, generic language and lacks a genuine description of the product's performance or features. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and originality, exhibiting templated language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is specific, descriptive and uses language that suggests the reviewer has actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and honest opinions about the headlamp's features and performance. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and offers no meaningful insights about the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and does not exhibit a genuine opinion. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and does not provide detailed information about the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, fails to elaborate on the product's features and performance, and uses generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specificity, lacks details about the product's performance or any useful insights beyond a subjective claim that the product did not meet expectations. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake

In [78]:
df_new.head(10)

,Binary_label,Category,source,text,is_synthetic
0,fake,Home_and_Kitchen,amazon,Air pressure was utter crap. I kept the lid o...,1
1,fake,Home_and_Kitchen,amazon,"Not what I expected, smaller than expected, bu...",1
2,fake,Home_and_Kitchen,amazon,We like a toaster that doesn't have the long h...,1
3,fake,Home_and_Kitchen,amazon,Love these pans they work great. The only prob...,1
4,fake,Home_and_Kitchen,amazon,I love the print on the back and the finish. I...,1
5,fake,Home_and_Kitchen,amazon,Bought this on a whim and it was the best purc...,1
6,fake,Home_and_Kitchen,amazon,"I admit I was leary of the suction, but I did ...",1
7,fake,Home_and_Kitchen,amazon,Purchased one as a gift and it was a very nice...,1
8,fake,Home_and_Kitchen,amazon,I wanted something to hold a bunch of pieces o...,1
9,fake,Home_and_Kitchen,amazon,I'm so happy I found this set and am very plea...,1

In [80]:
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

def evaluate_model(df, results):
    # Get true labels from the dataframe
    #y_true = df["deceptive"].tolist()
    y_true = df["Binary_label"].tolist()
    y_pred = results

    # Calculate metrics
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='weighted', pos_label=None)
    conf_matrix = confusion_matrix(y_true, y_pred)

    return accuracy, f1, conf_matrix

In [81]:
accuracy_one_shot, f1_one_shot, conf_matrix_one_shot = evaluate_model(df_new, one_shot_results)

print("=" * 50)
print("ONE-SHOT PROMPTING RESULTS")
print(Config.model)
print("=" * 50)
print("Accuracy:", accuracy_one_shot)
print("\nF1 Score:", f1_one_shot)
print("\nConfusion Matrix:")
print(conf_matrix_one_shot)
print("=" * 50)

==================================================
ONE-SHOT PROMPTING RESULTS
gemma:7b
==================================================
Accuracy: 0.54

F1 Score: 0.49776176438475817

Confusion Matrix:
[[100 300]
 [ 68 332]]
==================================================

## Few-Shot Prompting
Using multiple examples to guide the model's classification

In [82]:
llm = OllamaLLM(model=Config.model)

In [83]:
few_shot_prompt = PromptTemplate(
    input_variables=["text"],
    template=Config.few_shot_prompt_template
)

# Create few-shot chain
few_shot_chain = few_shot_prompt | llm

In [84]:
print(Config.few_shot_prompt_template)

    You are an expert at detecting real and fake reviews.


    Task: Classify the following review of a product that is listed on amazon as either "real" or "fake". Analyze the language and structure of the review,
	It should not be overly generic or templeted language,should not have sales-like wording and lacks details or specificity.

    Here are some examples:

    Example 1:
    Review: "Great Watch. I have had this watch for a long time and it works great. I have one in my car and the other in my office. The watch itself is a great watch and is very easy to use. It is a perfect size for my wrist and is very easy to wear. I have used it with a portable watch and I can tell the watch is very well made. I have worn it with a watch band and it is very comfortable. I will buy another one for my phone. I would highly recommend this watch.Perfect for my kids. I love them.These are super lightweight and lightweight. I have used them for a couple of months and they are still working great. I would definitely recommend them to my son for those times when he is not going to be wearing a helmet.These work great. I have used them for about a month and they are still doing great.Works as advertised.This is my second pair of glasses, and I really like the quality of the material. The material is thin and very soft, and it's comfortable to wear. The material is also very easy to clean, and I haven't had a problem with the plastic being damaged. I also have the odd case on my older pair, which I got for my husband when I was a kid. The fact that it's made of a durable material is"
    Classification: fake
    Example 2:
    Review: "I received these in and decided to go ahead and test these for strength and if it will be a good workout. I love the medium to the very strongest. The lighter exercise band when stretched rolled up a few times on me and I would have to unroll and start again. I guess because I was pulling it out so hard. The others did fine. I could feel the tightness with those as I stretched it out. I may lay flat and try it on my ankles and legs next. I left out of town so I have not been able to test it that way. But I assure you, you will feel it in your arms. I would consider buying these for my neighbor who also wants to work her arm muscles, because I do not want to loan mine out, as I will continue to use the tighter bands.
    Classification: real

    Now classify this review:
    Review: "{text}"
    Classify this review as either "real" or "fake" (respond with only one word):

In [85]:
# Classify reviews using few-shot prompting
# few_shot_results = []
# for r in reviews:
#     result = few_shot_chain.invoke({"text": r})
#     # Clean the output
#     label = result.strip().lower()
#     if " " in label:
#         label = label.split()[0]
#     label = label.strip('.,!?;:')
#     print(f"Raw output: {result} -> Cleaned: {label}")
#     few_shot_results.append(label)

In [87]:
# Classify each review
few_shot_results = []

for r in reviews:
    result = few_shot_chain.invoke({"text": r})
    
    label = result.strip().lower()
    
    # Keep only valid labels
    if "fake" in label:
        cleaned_label = "fake"
    elif "real" in label:
        cleaned_label = "real"
    else:
        print(f"Skipping invalid output: {result}")
        continue  # skip this review
    cleaned_label = cleaned_label.strip('.,!?;:')
    print(f"Raw output: {result} -> Cleaned: {cleaned_label}")
    few_shot_results.append(cleaned_label)

Raw output: Fake.

The review lacks specifics, general language and lacks a thorough analysis of the product's features or performance. -> Cleaned: fake
Raw output: Fake.

The review lacks details and specifics, uses very general language, and lacks a genuine analysis of the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, uses generic language, and lacks detailed analysis or personal experience. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks detail. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, uses general language, and lacks a detailed analysis of the product's features or performance. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, generic language, and lacks a personal touch. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and honest feedback about the product's usability. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language, and lacks a genuine analysis of the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and generic language. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and uses generic language. -> Cleaned: fake
Raw output: Fake.

The review lacks details, specifics, and uses general language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language, and lacks a detailed analysis of the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details or specificity, uses generic language, and has a templated structure. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks details, specificity and originality. It uses generic language and contains grammatical errors. -> Cleaned: fake
Raw output: Fake.

The review lacks specific details or personal experiences, and uses generic language commonly found in fake reviews. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal opinion about the product, indicating authenticity. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and addresses a minor design issue, suggesting genuine experience and thoughtful observation. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and descriptive language suggesting genuine experience and opinion. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and honest opinions about the product's functionality and performance. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and does not provide detailed information about the product. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, uses generic language, and lacks a personal touch or detailed analysis of the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, uses generic language, and lacks a genuine descriptive analysis of the product's features or functionality. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and uses generic language, indicating it is likely fake. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specific details, generic language, and does not provide any credible evidence to support its claims. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, uses generic language, and lacks a personal touch. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and does not exhibit genuine insights or experiences related to the product. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, lacks detail and uses very generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks a detailed analysis of the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity, lacks sales-like wording, and uses overly generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experience, suggesting authenticity. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experience about the product, indicating genuine feedback. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the size, feel, and fit of the case, indicating genuine experience and observation. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details or specifics and uses general language, suggesting it's fake. -> Cleaned: fake
Raw output: Real.

The review provides specific details and honest feedback about the product's thickness and quality, indicating a genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and exhibits inconsistencies in tone and structure. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, sales-like language, and details. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, uses repetitive language, and avoids expressing any concrete opinions or experiences with the lens. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, uses generic language, and lacks a personal touch or detailed analysis of the product's features or performance. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and uses general language, suggesting it's not a genuine review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experience, indicating authenticity. -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language. -> Cleaned: fake
Raw output: Real.

The review provides specific details and expresses a personal opinion, indicating that it is likely genuine. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks detailed analysis or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and problems encountered, indicating genuine experience. -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks a genuine analysis of the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specific details or analysis of the product's performance, and uses general and unhelpful language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experiences, indicating genuine feedback. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and technical language indicating genuine experience and knowledge of the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and analysis of the product's performance with different flashes, indicating genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experience, indicating genuine feedback. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specific details or personal experiences, and uses generic language commonly found in fake reviews. -> Cleaned: fake
Raw output: Fake.

The review lacks details, specificity, and does not provide any meaningful insights about the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal opinions about the product's functionality and comfort, suggesting genuine experience. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real.

The review is detailed, specific and honest in its criticism of the product's durability issues after three years of use. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and expresses a general opinion without providing any meaningful insights or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and uses very generic language. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, originality, and personal insights, indicating a templated or automated composition. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and generalizes the story without providing any concrete details or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specific details or analysis of the movie, using generic and repetitive language. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and uses generic, repetitive language. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, originality, and analytical language. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, originality, and analytical language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and lacks an analysis of the movie's qualities. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, generic language and does not demonstrate a genuine opinion. -> Cleaned: fake
Raw output: Fake.

The review is excessively repetitive and lacks any specific details or analysis of the movie's qualities. -> Cleaned: fake
Raw output: Fake.

The review lacks details or specificity and uses very generic language. -> Cleaned: fake
Raw output: Fake.

The review uses excessive repetition and lacks specificity or personal insights. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language, and lacks a genuine analysis of the movie's qualities. -> Cleaned: fake
Raw output: Fake.

The review lacks specific details or analysis of the movie's quality, and uses general and uninformative language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, sales-like wording, and details. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and uses generic language. -> Cleaned: fake
Raw output: Fake.

The review uses very generic and templated language, lacks details or specificity, and exhibits an overly enthusiastic tone. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, generic language and lacks a personal touch. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specific details or analysis of the movie's elements, relying on generic and superlative language. -> Cleaned: fake
Raw output: Fake.

The review lacks details or specificity and uses very generic language. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity, and personal experiences, indicating that it is likely a fabricated review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks personal opinion or experience. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and demonstrates a generic, templated language pattern often associated with fake reviews. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, generic language and lacks a genuine opinion. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specific details, generic language, and lacks a genuine tone. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal opinions about the James Bond movies. -> Cleaned: real
Raw output: Fake.

The review lacks specifics and reads like a promotional ad rather than an objective review. -> Cleaned: fake
Raw output: Real.

The review provides a personal and thoughtful opinion about the video, indicating that it is a genuine response. -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generalizes heavily and uses outdated language. -> Cleaned: fake
Raw output: Fake.

The review uses overly generic and templated language, lacks details or specificity, and uses sales-like wording. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is intentionally humorous and lacks genuine feedback on the product. -> Cleaned: fake
Raw output: Real.

The review provides detailed analysis and personal opinions about the movie, indicating a genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and analysis of the movie's elements, indicating a genuine opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and originality. It simply suggests that people who enjoyed Clash of the Titans will likely enjoy this product without offering any concrete information about the product itself. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides a thoughtful analysis of the video content, highlighting specific issues with production quality and delivery. -> Cleaned: real
Raw output: Fake.

The review lacks details and specifics, uses generic language, and exhibits a lack of depth. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real.

The review provides thoughtful critique of the movie's plot, character development and action sequences, suggesting that while it's not exceptional, it has redeeming qualities. -> Cleaned: real
Raw output: Real.


In [88]:
accuracy_few_shot, f1_few_shot, conf_matrix_few_shot = evaluate_model(df_new, few_shot_results)

print("=" * 50)
print("FEW-SHOT PROMPTING RESULTS")
print(Config.model)
print("=" * 50)
print("Accuracy:", accuracy_few_shot)
print("\nF1 Score:", f1_few_shot)
print("\nConfusion Matrix:")
print(conf_matrix_few_shot)
print("=" * 50)

==================================================
FEW-SHOT PROMPTING RESULTS
gemma:7b
==================================================
Accuracy: 0.61

F1 Score: 0.5924525344358014

Confusion Matrix:
[[161 239]
 [ 73 327]]
==================================================

## Compare All Approaches
Compare zero-shot, one-shot, and few-shot results

In [89]:
# Compare all approaches
comparison_df = pd.DataFrame({
    'Approach': ['Zero-Shot', 'One-Shot', 'Few-Shot'],
    'Accuracy': [accuracy, accuracy_one_shot, accuracy_few_shot],
    'F1 Score': [f1, f1_one_shot, f1_few_shot]
})

print("=" * 60)
print("COMPARISON OF ALL PROMPTING APPROACHES")
print("=" * 60)
print(comparison_df.to_string(index=False))
print("=" * 60)

# Find best approach
best_idx = comparison_df['Accuracy'].idxmax()
best_approach = comparison_df.loc[best_idx, 'Approach']
best_accuracy = comparison_df.loc[best_idx, 'Accuracy']
print(f"\nBest Approach: {best_approach} (Accuracy: {best_accuracy:.4f})")

============================================================
COMPARISON OF ALL PROMPTING APPROACHES
============================================================
 Approach  Accuracy  F1 Score
Zero-Shot   0.51875  0.404024
 One-Shot   0.54000  0.497762
 Few-Shot   0.61000  0.592453
============================================================

Best Approach: Few-Shot (Accuracy: 0.6100)

## Results With context for categories

In [90]:
pip install -r requirements.txt

Defaulting to user installation because normal site-packages is not writeable

Requirement already satisfied: pandas in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: pydantic in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.12.5)
Requirement already satisfied: langchain in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.3.27)
Requirement already satisfied: langchain-core in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.3.80)
Requirement already satisfied: langchain-community in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.3.31)
Requirement already satisfied: langchain-ollama in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.3.10)
Requirement already satisfied: scikit-learn in /home/bumu60du/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (1.6.1)
Requirement already satisfied: numpy>=1.22.4 in /home/bumu60du/.local/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/bumu60du/.local/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/bumu60du/.local/lib/python3.9/site-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic->-r requirements.txt (line 2)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic->-r requirements.txt (line 2)) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic->-r requirements.txt (line 2)) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic->-r requirements.txt (line 2)) (0.4.2)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (0.3.11)
Requirement already satisfied: langsmith>=0.1.17 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (0.4.37)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (2.0.44)
Requirement already satisfied: requests<3,>=2 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (2.32.5)
Requirement already satisfied: PyYAML>=5.3 in /usr/lib64/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (5.4.1)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/lib/python3.9/site-packages (from langchain->-r requirements.txt (line 3)) (4.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-core->-r requirements.txt (line 4)) (9.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-core->-r requirements.txt (line 4)) (1.33)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-core->-r requirements.txt (line 4)) (25.0)
Requirement already satisfied: jsonpointer>=1.9 in /home/bumu60du/.local/lib/python3.9/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->-r requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /home/bumu60du/.local/lib/python3.9/site-packages (from langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (0.25.0)
Requirement already satisfied: anyio in /home/bumu60du/.local/lib/python3.9/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (4.11.0)
Requirement already satisfied: certifi in /home/bumu60du/.local/lib/python3.9/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /home/bumu60du/.local/lib/python3.9/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (1.0.9)
Requirement already satisfied: idna in /usr/lib/python3.9/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (2.10)
Requirement already satisfied: h11>=0.16 in /home/bumu60du/.local/lib/python3.9/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/bumu60du/.local/lib/python3.9/site-packages (from requests<3,>=2->langchain->-r requirements.txt (line 3)) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests<3,>=2->langchain->-r requirements.txt (line 3)) (1.26.5)
Requirement already satisfied: greenlet>=1 in /home/bumu60du/.local/lib/python3.9/site-packages (from SQLAlchemy<3,>=1.4->langchain->-r requirements.txt (line 3)) (3.2.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-community->-r requirements.txt (line 5)) (3.13.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-community->-r requirements.txt (line 5)) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-community->-r requirements.txt (line 5)) (2.11.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-community->-r requirements.txt (line 5)) (0.4.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r requirements.txt (line 5)) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (0.9.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->-r requirements.txt (line 5)) (1.2.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->-r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied: ollama<1.0.0,>=0.5.3 in /home/bumu60du/.local/lib/python3.9/site-packages (from langchain-ollama->-r requirements.txt (line 6)) (0.6.1)
Requirement already satisfied: scipy>=1.6.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from scikit-learn->-r requirements.txt (line 7)) (1.10.1)
Requirement already satisfied: joblib>=1.2.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from scikit-learn->-r requirements.txt (line 7)) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/bumu60du/.local/lib/python3.9/site-packages (from scikit-learn->-r requirements.txt (line 7)) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/bumu60du/.local/lib/python3.9/site-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /home/bumu60du/.local/lib/python3.9/site-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain->-r requirements.txt (line 3)) (1.3.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [92]:
from prompt_category_context import Config

In [93]:
print(Config.zero_shot_prompt_template)

    You are an expert at detecting fake and real reviews.

    Task: Classify the following review of a product that is listed on amazon as either "fake" or "real". Analyze the language and structure of the review,
	It should not be overly generic or templeted language,should not have sales-like wording.

    The products reviewed may belong to categories such as:
    Home and Kitchen, Sports and Outdoors, Electronics, Beauty, Clothing, Books, and similar retail categories.


    Review: "{text}"

    Classify this review as either "fake" or "real" (respond with only one word):

### Zero shot

In [95]:
prompt = PromptTemplate(
    input_variables=["text"], # the placeholder to be replaced based on prompt template
    template=Config.zero_shot_prompt_template
)

# Load small model
llm = OllamaLLM(model=Config.model)

# Create chain using pipe operator (modern LangChain syntax)
chain = prompt | llm

In [96]:
# Classify each review
results = []

for r in reviews:
    result = chain.invoke({"text": r})
    
    label = result.strip().lower()
    
    # Keep only valid labels
    if "fake" in label:
        cleaned_label = "fake"
    elif "real" in label:
        cleaned_label = "real"
    else:
        print(f"Skipping invalid output: {result}")
        continue  # skip this review
    cleaned_label = cleaned_label.strip('.,!?;:')
    print(f"Raw output: {result} -> Cleaned: {cleaned_label}")
    results.append(cleaned_label)

Raw output: Real -> Cleaned: real

Raw output: Real.

The review provides specific details about the product's size and materials, indicating that the reviewer has actually used the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses personal language and expresses genuine enthusiasm, suggesting it is authentic. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's functionality and its application for small fruits and vegetables, indicating genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses descriptive language and expresses genuine enthusiasm for the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses descriptive language that goes beyond simply stating that the product is good or that it works well. It also expresses a personal connection to the product and suggests that the reviewer is genuinely happy with it. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's performance and design, indicating genuine experience and opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses specific and descriptive language that suggests genuine experience and knowledge of the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and offers irrelevant information about heat deflectors, suggesting it's not a genuine review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about a previous product and expresses genuine satisfaction. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and indicates sustained use over time. -> Cleaned: real
Raw output: Real.

The review provides specific and detailed information about the product, indicating that the reviewer has actual experience with it. The language is descriptive and technical, suggesting a genuine understanding of the product's features and functionality. -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's functionality and materials, suggesting genuine experience with the product. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about a problem with the product and how it affects the reviewer's use of the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific information about the product, indicating that the reviewer has actual experience using it. The language is also honest and unbiased. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and offers no meaningful insights about the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's size, fit, and comfort, suggesting that the reviewer has actually used the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The language is specific and descriptive, indicating that the reviewer has actually used the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and descriptive feedback on the product's features and performance, including both pros and cons. It also includes personal experiences and reasons for returning the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a personal opinion that is neither overly positive nor negative. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's usability and suggests it's suitable for beginners, indicating genuine experience and opinion. -> Cleaned: real
Raw output: Real.

The review expresses a negative experience with the product and requests a refund or replacement. This suggests that the reviewer is a legitimate customer who had a problem with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks coherence and does not provide a genuine evaluation of the product's functionality or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific information about the product's performance and durability, suggesting that the reviewer has actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's assembly and quality issues, suggesting firsthand experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed analysis of the product's features and performance, indicating genuine experience and knowledge about the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's performance in harsh winter conditions, indicating actual experience with the product. -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's fit and durability, indicating actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The language is concise and straightforward, without any exaggerated or unnatural claims. It simply states that the product is a ruler that can measure spokes and that it was affordable. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific information about a product (Arock board) and how it compares to a previous product (with an AC adapter). This suggests a genuine experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the bag's construction, dimensions, compatibility, and features, suggesting a genuine experience and opinion. -> Cleaned: real
Raw output: Real.

The review provides a concise and factual description of the product's functionality and a minor issue with the included tool. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's compatibility with different models of Macbooks and explains that the reviewer had to replace their case, indicating genuine experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's functionality and performance, indicating that the reviewer has actually used the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is concise yet informative, suggesting that the product is easy to install and delivers good value for money. It also acknowledges a minor drawback without resorting to hyperbole or exaggerated claims. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's functionality and sound quality, indicating genuine experience and knowledge of the camera's sound system. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review contains specific details and technical language suggesting actual experience and technical knowledge. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a clear and specific disappointment with the product's inability to resolve the problem it was intended to solve. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about how the product works with a particular device and mentions a known issue with that device. -> Cleaned: real
Raw output: Real.

The review provides specific technical details and benchmarks, indicating genuine knowledge of the product and its performance. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses genuine enthusiasm and plans to purchase additional items. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and technical details about the product's performance with different flash units, indicating an understanding of the product and its features. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses honest language and expresses a genuine opinion after having used the product for a year. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific feedback on the product's performance, highlighting both its strengths and weaknesses. It is well-written and avoids generic or sales-like language. -> Cleaned: real
Raw output: Real.

The review exhibits detailed knowledge of electrical wire specifications and expresses a genuine opinion based on personal experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a personal opinion about the product's value for money and its performance. It does not contain any unusual or suspicious language or syntax. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review exhibits detailed knowledge of the film's literary sources and technical aspects, suggesting a genuine interest in the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review focuses almost exclusively on praising the script, without offering any meaningful commentary on the product itself. This suggests that the review is not genuine. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, offers only generic critiques of the various elements of the movie and employs repetitive language. -> Cleaned: fake
Raw output: Real.

The review provides a personal and thoughtful opinion about the product, indicating genuine experience and enjoyment. -> Cleaned: real
Raw output: Fake.

The review uses excessive repetition and generic language, suggesting a lack of authenticity. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a genuine opinion and uses natural language. -> Cleaned: real
Raw output: Fake.

The review consists of excessive repetition of the word "thriller," suggesting a lack of genuine enthusiasm or insightful analysis. -> Cleaned: fake
Raw output: Fake.

The review is excessively repetitive and lacks genuine insight or originality. -> Cleaned: fake
Raw output: Real.

The review provides detailed and thoughtful analysis of the movie's characters, plot, and acting, suggesting a genuine opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is excessively repetitive, indicating a lack of authenticity and genuine opinion. -> Cleaned: fake
Raw output: Real.

The review expresses a genuine opinion about the movie's story and characters, indicating that the reviewer actually watched the movie. -> Cleaned: real
Raw output: Fake.

The review uses excessive and repetitive language praising every aspect of the film, which suggests a lack of authenticity and professionalism. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and descriptive criticisms of the product's picture quality and suitability for the intended audience. -> Cleaned: real
Raw output: Fake.

The review uses very generic and templated language, lacks specificity, and exhibits an unnatural enthusiasm that is not consistent with genuine user experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks detail and offers no useful insight beyond a generic statement of liking the movie. -> Cleaned: fake
Raw output: Fake.

The review lacks specificity and originality, and uses exaggerated and generic language. -> Cleaned: fake
Raw output: Real.

The language is enthusiastic and specific, indicating genuine excitement for the product. -> Cleaned: real
Raw output: Fake.

The review reads like a script or synopsis of a pirate adventure story rather than an actual product review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses repetitive language and lacks specificity, suggesting it is likely a fake review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a genuine opinion about the product, with specific criticisms of the plot, pacing, and lack of substance. -> Cleaned: real
Raw output: Real.

The review uses personal humor and references a well-known movie, indicating a genuine opinion rather than a paid promotion. -> Cleaned: real
Raw output: Real.

The review is well-written and provides thoughtful analysis of the movie, including specific plot points and their shortcomings. It also expresses genuine emotions and opinions, rather than simply promoting the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and uses excessive exclamation points and superlatives, suggesting a fabricated or promotional nature. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks substance and uses humorous language that suggests it is not a genuine assessment of the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review exhibits thoughtful analysis of the movie's plot and characters, indicating genuine interest and understanding of the film. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.


In [97]:
# Classify each review
results = []

for r in reviews:
    result = chain.invoke({"text": r})
    
    label = result.strip().lower()
    
    # Keep only valid labels
    if "fake" in label:
        cleaned_label = "fake"
    elif "real" in label:
        cleaned_label = "real"
    else:
        print(f"Skipping invalid output: {result}")
        continue  # skip this review
    cleaned_label = cleaned_label.strip('.,!?;:')
    print(f"Raw output: {result} -> Cleaned: {cleaned_label}")
    results.append(cleaned_label)

Raw output: Real.

The review provides specific details about the product's air pressure and lid durability, indicating genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and informative details about the product's features and functionality, suggesting firsthand experience and attention to detail. -> Cleaned: real
Raw output: Real.

The review provides a specific description of the product's scent and a minor inconvenience during installation, suggesting genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses personal language and describes a specific experience related to the product. -> Cleaned: real
Raw output: Real.

The review provides specific and useful information about the product's size and opening, suggesting that the reviewer has actually used the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The language is specific and informative, indicating actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and descriptive details about the quality and craftsmanship of the brushes, suggesting genuine experience and opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's design and functionality, suggesting genuine experience and opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and a long-term perspective, suggesting genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific information about the product's features and functionality, suggesting that the reviewer has actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and descriptive language about the scent and coverage of the product, suggesting genuine experience and knowledge of the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The language is personal and specific, demonstrating genuine experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's functionality and aesthetics, suggesting genuine experience and opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experience, indicating genuine use and opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and exhibits a lack of understanding of the product's intended use. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and indicates sustained use over a period of two years, suggesting authenticity. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks coherence and common sense. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and offers no meaningful insights about the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses specific details about a particular product model and its functionality, suggesting actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides a concise and balanced opinion, expressing satisfaction with the quality of the product without resorting to hyperbole or sales-like language. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific observations about the product's features and performance, suggesting genuine experience and knowledge. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed and specific feedback on the product's quality, indicating that the reviewer has actually used the product and has a genuine experience to share. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks detail and plausibility. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is concise but provides enough information to understand that the product works as intended. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses specific language related to gun manufacturing and materials, indicating knowledge of the product. It also avoids generic or templated language typically associated with fake reviews. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is specific, provides a clear opinion, and lacks generic or templated language. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the compatibility of the case with different Macbook models and mentions a recent case replacement experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a genuine opinion with nuanced language and avoids generic or sales-like wording. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's performance and challenges encountered, suggesting genuine experience and opinion. -> Cleaned: real
Raw output: Real.

The review provides specific information about the product's functionality and purchase experience, suggesting a genuine opinion. -> Cleaned: real
Raw output: Real.

The review provides specific details and expresses genuine satisfaction, indicating a real experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific, descriptive feedback on the keyboard's features and functionality, suggesting that the reviewer has actually used and evaluated the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides a concise and informative assessment of the product, indicating that it is a good value for money. The language used is clear and concise, suggesting that the reviewer is a genuine consumer. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and indicates that the product has been used for 2 years without any issues. -> Cleaned: real
Raw output: Real.

The review provides specific and detailed information about the product's technical issues, suggesting that the reviewer actually experienced these problems. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a specific and negative experience with the product, providing details about its failure to resolve the intended issue. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides detailed information about the product's construction and performance, indicating genuine experience and knowledge about the product. -> Cleaned: real
Raw output: Real.

The review provides specific, detailed comments about comfort, sound quality, and construction, indicating genuine experience and opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's functionality and value for money, suggesting genuine experience and opinion. -> Cleaned: real
Raw output: Real.

The review expresses a genuine experience and clearly explains the limitations of the product. -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's compatibility with a particular device and includes a mention of an instructional video that assisted in the process. This suggests a genuine experience and expertise. -> Cleaned: real
Raw output: Real.

The review provides a detailed analysis of the product's performance, installation process, and customer service response. It also includes personal experiences and comparisons to other coolers. -> Cleaned: real
Raw output: Real.

The review provides specific technical details and analysis of a product's compatibility issues, suggesting genuine experience and knowledge. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product's functionality and durability, suggesting that the reviewer has actually used the product. -> Cleaned: real
Raw output: Real.

The language is specific and knowledgeable about Hoya lens, indicating actual experience with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review demonstrates a genuine appreciation for exceptional customer service and technical expertise. It avoids generic language and sales-like wording. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses specific and descriptive language suggesting genuine experience and familiarity with the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a personal opinion and provides a concise explanation. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review focuses almost exclusively on praising the acting and script, using redundant and unnatural language. It lacks any mention of the product itself, suggesting an incentivized review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and originality, exhibiting repetitive and generic language with no meaningful insights or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is repetitive and uses excessive and unnatural language to express affection for the show. -> Cleaned: fake
Raw output: Real.

The review provides a thoughtful analysis of the book's adaptation, noting similarities in the story but differences in the characters. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is excessively repetitive and lacks meaningful content beyond simply listing the word "thriller" multiple times. -> Cleaned: fake
Raw output: Fake.

The review is overly repetitive and uses a formulaic structure, suggesting it's a fake review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is excessively repetitive and uses an unnatural number of superlatives, indicating a lack of authenticity. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is excessively laudatory and repetitive, suggesting a lack of authenticity. -> Cleaned: fake
Raw output: Real.

The review provides a thoughtful analysis of the movie's characters and their lack of chemistry, suggesting that it's a genuine opinion rather than a promotional or exaggerated statement. -> Cleaned: real
Raw output: Real.

The review exhibits genuine analysis and coherent sentence structure, indicating a genuine opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses exaggerated language and lacks sincerity. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and offers no useful information about the product's features or performance. -> Cleaned: fake
Raw output: Fake.

The review lacks specificity and originality, exhibiting generic and repetitive language commonly found in fake reviews. -> Cleaned: fake
Raw output: Real.

The language used is enthusiastic and suggests that the reviewer is a genuine fan of Hanna-Barbera. -> Cleaned: real
Raw output: Fake.

The review reads like a fictional story rather than an actual product review. -> Cleaned: fake
Raw output: Real.

The review uses complete sentences and paragraphs, providing thoughtful commentary on the movie's historical significance and production quality. It avoids generic or sales-like language. -> Cleaned: real
Raw output: Real.

The review demonstrates a detailed understanding of the relationship between language and emotions, specifically referencing the use of different alphabets in movies. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is overly repetitive and lacks genuine insights or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides a thoughtful analysis of the movie, discussing its plot points and emotional impact. It also compares it to another movie, suggesting that it is similar but with minor differences. This level of detail and nuance suggests that the review is written by a genuine movie enthusiast. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review contains personal opinions and references to specific pricing information, suggesting authenticity. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review exhibits detailed knowledge of film history and specific references to a particular comedian's works, suggesting genuine interest and expertise in the subject matter. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses language that suggests it is not a serious review of the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review uses exaggerated and nonsensical language, suggesting it is not a genuine and thoughtful opinion. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review uses specialized vocabulary related to film and cinematography, suggesting knowledge of the subject matter. -> Cleaned: real
Raw output: Real -> Cleaned: real

In [98]:
# def clean_label(text):
#     return text.strip().lower().split()[0].strip('.,!?;:')
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

def evaluate_model(df, results):
    # Get true labels from the dataframe
    #y_true = df["deceptive"].tolist()
    y_true = df["Binary_label"].tolist()
    y_pred = results

    # Calculate metrics
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='weighted', pos_label=None)
    conf_matrix = confusion_matrix(y_true, y_pred)

    return accuracy, f1, conf_matrix

In [99]:
accuracy, f1, conf_matrix = evaluate_model(df_new, results)

print("=" * 50)
print("ZERO-SHOT PROMPTING RESULTS WITH CONTEXT")
print("=" * 50)
print("Accuracy:", accuracy)
print("\nF1 Score:", f1)
print("\nConfusion Matrix:")
print(conf_matrix)
print("=" * 50)

==================================================
ZERO-SHOT PROMPTING RESULTS WITH CONTEXT
==================================================
Accuracy: 0.51125

F1 Score: 0.3914100880393015

Confusion Matrix:
[[ 27 373]
 [ 18 382]]
==================================================

## One Shot

In [100]:
llm = OllamaLLM(model=Config.model)

In [101]:
print(Config.one_shot_prompt_template)

     You are an expert at detecting fake and real reviews.

    Task: Classify the following review of a product that is listed on amazon as either "real" or "fake". Analyze the language and structure of the review,
	It should not be overly generic or templeted language,should not have sales-like wording and lacks details or specificity.

    The products reviewed may belong to categories such as:
    Home and Kitchen, Sports and Outdoors, Electronics, Beauty, Clothing, Books, and similar retail categories.

    Example:
    Review: "Great Watch. I have had this watch for a long time and it works great. I have one in my car and the other in my office. The watch itself is a great watch and is very easy to use. It is a perfect size for my wrist and is very easy to wear. I have used it with a portable watch and I can tell the watch is very well made. I have worn it with a watch band and it is very comfortable. I will buy another one for my phone. I would highly recommend this watch.Perfect for my kids. I love them.These are super lightweight and lightweight. I have used them for a couple of months and they are still working great. I would definitely recommend them to my son for those times when he is not going to be wearing a helmet.These work great. I have used them for about a month and they are still doing great.Works as advertised.This is my second pair of glasses, and I really like the quality of the material. The material is thin and very soft, and it's comfortable to wear. The material is also very easy to clean, and I haven't had a problem with the plastic being damaged. I also have the odd case on my older pair, which I got for my husband when I was a kid. The fact that it's made of a durable material is"
    Category : Watches
    Classification: fake

    Now classify this review:
    Review: "{text}"
    Classify this review as either "real" or "fake" (respond with only one word):

In [102]:
one_shot_prompt = PromptTemplate(
    input_variables=["text"],
    template = Config.one_shot_prompt_template
)
# Create one-shot chain
one_shot_chain = one_shot_prompt | llm

In [103]:
# Classify each review
one_shot_results = []

for r in reviews:
    result = one_shot_chain.invoke({"text": r})
    
    label = result.strip().lower()
    
    # Keep only valid labels
    if "fake" in label:
        cleaned_label = "fake"
    elif "real" in label:
        cleaned_label = "real"
    else:
        print(f"Skipping invalid output: {result}")
        continue  # skip this review
    cleaned_label = cleaned_label.strip('.,!?;:')
    print(f"Raw output: {result} -> Cleaned: {cleaned_label}")
    one_shot_results.append(cleaned_label)

Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is detailed and specific, providing personal experiences and observations about the product's features and performance. It lacks generic or templated language and sales-like wording. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details and specificity, and uses sales-like wording. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details, specifics and uses general language suggesting it's not from a genuine user. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, originality, and fails to convey any genuine experience or opinion about the lens. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real.

The review provides specific details and criticisms of the product's performance and durability over a period of three years, indicating a genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and focuses solely on repeating generic statements about the quality of the acting and script without providing any concrete evidence or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specificity, details, and personal experiences, indicating a likely fabricated review. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, does not provide any concrete information or analysis of the movie's qualities, and primarily repeats the same sentiment. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and originality, exhibiting templated language and redundant repetition. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details and specificity, and uses very generic language. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, lacks analysis of the movie's elements, and uses generic language. -> Cleaned: fake
Raw output: Fake.

The review lacks specific details or analysis of the product, suggesting a lack of genuine experience or knowledge about the product. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and details about the product, resembling a generic promotional statement. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity, lacks details about the product, and uses generic language commonly found in fake reviews. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is well-written and provides thoughtful analysis of the film. It uses specific examples and comparisons to support its arguments. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and demonstrates templated language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is detailed, specific and provides personal experiences and observations about the product. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specificity, lacks detail, and uses generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and details, and uses very general language. -> Cleaned: fake
Raw output: Real.

The review provides specific details and criticisms about the product, indicating genuine experience and thoughtful observation. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real

In [104]:
accuracy_one_shot, f1_one_shot, conf_matrix_one_shot = evaluate_model(df_new, one_shot_results)

print("=" * 50)
print("ONE-SHOT PROMPTING RESULTS WITH CONTEXT")
print("=" * 50)
print("Accuracy:", accuracy_one_shot)
print("\nF1 Score:", f1_one_shot)
print("\nConfusion Matrix:")
print(conf_matrix_one_shot)
print("=" * 50)

==================================================
ONE-SHOT PROMPTING RESULTS WITH CONTEXT
==================================================
Accuracy: 0.5625

F1 Score: 0.5062599188855581

Confusion Matrix:
[[ 90 310]
 [ 40 360]]
==================================================

## Few Shot

In [105]:
llm = OllamaLLM(model=Config.model)

In [106]:
print(Config.one_shot_prompt_template)

     You are an expert at detecting fake and real reviews.

    Task: Classify the following review of a product that is listed on amazon as either "real" or "fake". Analyze the language and structure of the review,
	It should not be overly generic or templeted language,should not have sales-like wording and lacks details or specificity.

    The products reviewed may belong to categories such as:
    Home and Kitchen, Sports and Outdoors, Electronics, Beauty, Clothing, Books, and similar retail categories.

    Example:
    Review: "Great Watch. I have had this watch for a long time and it works great. I have one in my car and the other in my office. The watch itself is a great watch and is very easy to use. It is a perfect size for my wrist and is very easy to wear. I have used it with a portable watch and I can tell the watch is very well made. I have worn it with a watch band and it is very comfortable. I will buy another one for my phone. I would highly recommend this watch.Perfect for my kids. I love them.These are super lightweight and lightweight. I have used them for a couple of months and they are still working great. I would definitely recommend them to my son for those times when he is not going to be wearing a helmet.These work great. I have used them for about a month and they are still doing great.Works as advertised.This is my second pair of glasses, and I really like the quality of the material. The material is thin and very soft, and it's comfortable to wear. The material is also very easy to clean, and I haven't had a problem with the plastic being damaged. I also have the odd case on my older pair, which I got for my husband when I was a kid. The fact that it's made of a durable material is"
    Category : Watches
    Classification: fake

    Now classify this review:
    Review: "{text}"
    Classify this review as either "real" or "fake" (respond with only one word):

In [107]:
few_shot_prompt = PromptTemplate(
    input_variables=["text"],
    template=Config.few_shot_prompt_template
)

# Create few-shot chain
few_shot_chain = few_shot_prompt | llm

In [108]:
# Classify each review
few_shot_results = []

for r in reviews:
    result = few_shot_chain.invoke({"text": r})
    
    label = result.strip().lower()
    
    # Keep only valid labels
    if "fake" in label:
        cleaned_label = "fake"
    elif "real" in label:
        cleaned_label = "real"
    else:
        print(f"Skipping invalid output: {result}")
        continue  # skip this review
    cleaned_label = cleaned_label.strip('.,!?;:')
    print(f"Raw output: {result} -> Cleaned: {cleaned_label}")
    few_shot_results.append(cleaned_label)

Raw output: Fake.

The review lacks specifics, generic language, and fails to provide useful information about the product's features or performance. -> Cleaned: fake
Raw output: Fake.

The review lacks details and specificity, and uses very general language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specific details and uses overly generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and demonstrates generic language, suggesting it is fabricated. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks a detailed analysis of the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, uses generic language, and expresses little to no genuine opinion or knowledge about the product. -> Cleaned: fake
Raw output: Real.

The review provides specific details and honest opinions about the product's features and performance. -> Cleaned: real
Raw output: Fake.

The review lacks specifics, general language, and fails to provide any detailed information or personal experiences related to the product. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and expresses genuine enthusiasm for the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and personal experiences and opinions about the product, indicating genuine use and satisfaction. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and honest opinions about the product's features, performance, and design flaws. It lacks generic or templated language and avoids sales-like wording. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and analysis of the product's features and performance, indicating genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, generalities and does not provide detailed analysis or personal experiences. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, sales-like wording, and detailed analysis. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real.

The review provides specific details and personal opinions about the weight belt, indicating genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language, suggesting it's fake. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experience, suggesting genuine feedback. -> Cleaned: real
Raw output: Fake.

The review lacks details, specificity and uses general language. It also sounds like a boilerplate response to negative feedback. -> Cleaned: fake
Raw output: Real.

The review provides specific details and observations about the product's performance in different environments, suggesting genuine experience and knowledge. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and praises the quality, durability, and finish of the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language, suggesting it's fake. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and personal experience with the lens, indicating a genuine opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific and concise information about the product's functionality and minor issue without using overly generic or promotional language. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, originality, and genuine opinions. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, sales-like wording and general language. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks details and specifics, and uses general and vague language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks details about the product's performance or usability. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses general language without providing any credible evidence or detailed observations about the product's performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and technical information about the adapter's compatibility with the Bose Wave radio and Sirius XM. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details about the product and expresses a genuine opinion. -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses vague language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and technical knowledge about the product's compatibility with different flash sizes, indicating genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific feedback on the product's performance and audio quality, indicating genuine experience and opinion. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real.

The review provides specific details and criticisms of the product's performance, suggesting genuine experience. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, sales-like language and generalizes issues without providing meaningful insights. -> Cleaned: fake
Raw output: Real.

The review expresses a personal opinion and provides specific details about the movie's storyline, acting, and feel. -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specific criticisms or praise of the movie, and uses very general and subjective language. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real.

The review is detailed and personal, and it lacks the templated language and sales-like wording often found in fake reviews. -> Cleaned: fake
Raw output: Fake.

The review is excessively repetitive and lacks specific details or analysis of the show. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic, repetitive language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is overly repetitive and lacks specific details or analysis of the movie's qualities. -> Cleaned: fake
Raw output: Real.

The review provides thoughtful analysis of the story and characters, indicating a genuine opinion. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, originality, and genuine insights. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics, generic language, and lacks a genuine analysis of the product's features or performance. -> Cleaned: fake
Raw output: Fake.

The review uses highly generic and templated language, lacks specifics or personal details, and exhibits an overly positive and promotional tone. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specific details or analysis of the movie's elements like plot, acting, or script. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity and details, and uses a very generic and templated language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specificity, fails to provide any concrete details about the movie, and employs repetitive language. -> Cleaned: fake
Raw output: Fake.

The review lacks details or specificity and uses very general language. -> Cleaned: fake
Raw output: Fake.

The review lacks specific details, uses general language, and lacks a personal touch. -> Cleaned: fake
Raw output: Fake.

The review lacks specificity and details, and exhibits a generic and templated language structure. -> Cleaned: fake
Raw output: Fake.

The review lacks specific details, exhibits generic language, and promotes the movie rather than offering an honest opinion. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is well-written and provides specific details about the product. It also contains personal opinions and insights. -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real.

The review exhibits detailed analysis and personal insights on the films and their themes. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is personal and specific, indicating that the reviewer has a genuine connection to the product. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses generic language. It also contradicts itself by stating that the product is made from photographs but not real footage. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review is well-written and provides a thoughtful analysis of the movie based on the source material. It also includes personal opinions and insights. -> Cleaned: real
Raw output: Fake.

The review lacks specifics and resembles a promotional blurb. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real.

The review expresses a personal opinion and provides a concise and nuanced analysis of the movie. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides thoughtful analysis and subjective opinions about the film, demonstrating genuine engagement with the subject matter. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review is overly sensationalist and lacks specific details or evidence to support its claims. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and sounds like a generic, promotional statement rather than an honest review. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specific details, uses generic language, and lacks sales-like wording. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics, generic language and lacks detailed analysis of the product's features or performance. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real.

The review provides specific details and technical language suggesting actual experience with the product. -> Cleaned: real
Raw output: Fake.

The review lacks details and specifics, uses generic language, and lacks a personal touch. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and uses generic language. -> Cleaned: fake
Raw output: Real.

The review provides specific details and personal experiences, indicating genuineness. -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and appears templated. -> Cleaned: fake
Raw output: Fake.

The review lacks specifics and uses very generic language. -> Cleaned: fake
Raw output: Fake -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Fake.

The review lacks specifics and uses vague language. -> Cleaned: fake
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real
Raw output: Real -> Cleaned: real

In [109]:
accuracy_few_shot, f1_few_shot, conf_matrix_few_shot = evaluate_model(df_new, few_shot_results)

print("=" * 50)
print("FEW-SHOT PROMPTING RESULTS WITH CONTEXT")
print("=" * 50)
print("Accuracy:", accuracy_few_shot)
print("\nF1 Score:", f1_few_shot)
print("\nConfusion Matrix:")
print(conf_matrix_few_shot)
print("=" * 50)

==================================================
FEW-SHOT PROMPTING RESULTS WITH CONTEXT
==================================================
Accuracy: 0.55

F1 Score: 0.5030061226884608

Confusion Matrix:
[[ 97 303]
 [ 57 343]]
==================================================